<?php
/**
 * Created by PhpStorm.
 * User: Coder
 * Date: 14.02.2019
 * Time: 14:44
 */

namespace frontend\widgets;


use common\models\Portfolio;

class PortfolioWidget extends \yii\base\Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $Portfolio = new Portfolio();
       $lst = $Portfolio->lst();
        $this->view->registerCssFile('/lib/owl-carousel/css/owl.carousel.css?v'.YII_V);
        $this->view->registerCssFile('/lib/owl-carousel/css/owl.theme.default.css?v'.YII_V);
        return $this->render('portfolioWidget',
            ['lst' => $lst]
        );

    }
}