<?php
/**
 * Created by PhpStorm.
 * User: Coder
 * Date: 14.02.2019
 * Time: 14:44
 */

namespace frontend\widgets;


use common\models\Portfolio;

class PortfolioWidget extends \yii\base\Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $Portfolio = new Portfolio();
        $Portfolio->lst();
        return $this->render('portfolioWidget');

    }
}